services:
  guessify-server:
    build: ./server
    ports:
      - "5001:8080"
    env_file:
      - .env
    networks:
      - internal
  guessify-front:
    build: ./front
    ports:
      - "3001:3000"
    networks:
      - internal

networks:
  internal:
    external: true
