services:
  guessify-server:
    build: ./server
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal
  guessify-front:
    build: ./front
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true
