export default {
  "br": {
      "authenticated": "Autenticado. Você pode fechar essa janela",
      "landing-title": "Você conhece as suas músicas?",
      "landing-description": "Faça o teste: Conecte sua conta do Spotify, escolha uma playlist/álbum e tente adivinhar a música o mais rapidamente!",
      "landing-login": "Entre com",
      "landing-continue": "Iniciar como",
      "landing-logout": "Sair",
      "landing-not": "Não é",
      "landing-about": "Sobre",
      "landing-tutorial": "Tutorial",
      "landing-goback": "Voltar",
      "landing-requires": "Spotify Premium necessário",
      "copyright-text1": "Guessify não possui associação com Spotify.",
      "copyright-text2": "Guessify não usa cookies nem rastreia seus dados.",
      "pregame-choose": "Escolha da sua biblioteca",
      "pregame-load": "ou utilize uma URL",
      "pregame-not-found": "Nenhuma álbum ou playlist encontrada",
      "contentbox-track": "música",
      "pregame-placeholder": "Clique em \"Compartilhar - Copiar link\" e cole aqui",
      "pregame-invalidurl": "URL inválida",
      "pregame-urlnotfound": "Playlist ou álbum não encontrada",
      "pregame-play": "Iniciar",
      "spotify-powered": "Fornecido por",
      "spotify-open": "Abrir em",
      "start-selected": "Playlist/Álbum selecionado:",
      "start-tip": "Dica:",
      "start-start": "Começar",
      "game-now-playing": "Tocando de: ",
      "game-double-click": "Clique duas vezes para escolher",
      "game-click-again": "Clique de novo",
      "game-click-again2": "para escolher",
      "game-listening": "O que está ouvindo?",
      "game-guess": "Escolher",
      "game-points": "pontos",
      "game-rounds": "rodadas",
      "game-correct": "Correto",
      "game-wrong": "Errado",
      "game-you-got": "Você ganhou ",
      "game-try-again": "Tente novamente!",
      "game-correct-track": "A música correta era:",
      "game-you-guessed": "Você escolheu:",
      "game-prenext": "Faltam",
      "game-next": "Próximo",
      "game-round": "rodada",
      "game-posnext": "",
      "game-endresults": "Resultados",
      "game-your-score": "Sua avaliação",
      "game-seconds": "segundos",
      "game-correct-guesses": "Escolhas corretas",
      "game-average": "Média para escolhas corretas",
      "game-total": "Tempo total",
      "game-rounds-of": "rodadas de",
      "game-share": "Copiar link",
      "game-playagain": "Testar novamente",
      "game-newgame": "Novo teste",
      "game-copied": "Copiado!"
  },
  "en": {
      "authenticated":"Authenticated. You can close this window",
      "landing-title": "Do you know your music?",
      "landing-description": "Let's test you: Connect with your Spotify account, choose a playlist/album and try to quickly guess the music!",
      "landing-login": "Login with",
      "landing-continue": "Continue as",
      "landing-logout": "Logout",
      "landing-not": "Not",
      "landing-about": "About",
      "landing-tutorial": "Tutorial",
      "landing-goback": "Go back",
      "landing-requires": "Requires Spotify Premium",
      "copyright-text1": "Guessify has no association with Spotify.",
      "copyright-text2": "Guessify has no cookies and no data tracking.",
      "pregame-choose": "Choose from your library",
      "pregame-load": "or load from an URL",
      "pregame-not-found": "No albums or playlist found",
      "contentbox-track": "track",
      "pregame-placeholder": "Click on \"Share - Copy Link\" and paste here",
      "pregame-invalidurl": "Invalid URL",
      "pregame-urlnotfound": "Could not find Playlist or Album",
      "pregame-play": "Start",
      "spotify-powered": "Powered by",
      "spotify-open": "Open in",
      "start-selected": "Playlist/Album selected:",
      "start-tip": "Tip:",
      "start-start": "Start",
      "game-now-playing": "Now playing from: ",
      "game-double-click": "Double click on a track to submit",
      "game-click-again": "Click again",
      "game-click-again2": "to submit",
      "game-listening": "What are you listening?",
      "game-guess": "Guess",
      "game-points": "points",
      "game-rounds": "rounds",
      "game-correct": "Correct",
      "game-wrong": "Wrong",
      "game-you-got": "You got ",
      "game-try-again": "Try again!",
      "game-correct-track": "The correct track was:",
      "game-you-guessed": "You guessed:",
      "game-prenext": "",
      "game-next": "Next",
      "game-round": "round",
      "game-posnext": " to go",
      "game-endresults": "End results",
      "game-your-score": "Your results",
      "game-seconds": "seconds",
      "game-correct-guesses": "Correct guesses",
      "game-average": "Average for correct guesses",
      "game-total": "Total time",
      "game-rounds-of": "rounds of",
      "game-share": "Share",
      "game-playagain": "Test again",
      "game-newgame": "New teste",
      "game-copied": "Copied!"
  }
}